### ISSUE TITLE
NakagamiRice.cpp       

### ISSUE THREAD

**Issue by alastairUK** [NTIA/p528#4]
https://github.com/NTIA/p528/blob/50d9c97d577f863ab3b7add84dcbead81bc7fd44/src/NakagamiRice.cpp#L29

ReShaper C++ is showing a potential issue ("Both sides of operator are equivalent [misc-redundant-expression]") with this line:

`data::NR_Data[i - i]`

I *think* this is a typo and it should read i-1

But the more I look at this code the more I think there is a general issue (could be wrong)

Looking at a test input of 

Result res{};
Main(1, 1.5, 1000, 1200, 0.01, &res);

and putting a breakpoint on the NakagamiRice function I think there are cases when the index goes negative (j == 0 so data::P[j - 1] is an issue)

You can better trap this by converting to use std::array or std::vector and running in debug and the debugger traps the issue

**Comment by wkozmaNTIA** [comment]
Thanks for the feedback.  This is currently being addressed through active input contributions in the US Study Group 3 review process.  If approved, it will be forwarded to ITU-R Study Group 3 for consideration and approval.
